### ISSUE TITLE
check sum value not correct.

### ISSUE THREAD

**Issue by venkateshv6** [vivekannan/Rift#1]
Generated Hex files checksum value not correct.

**Comment by vivekannan** [comment]
Sorry for the radio silence. Could you be a little bit more specific? Maybe you could post the assembly source which resulted in the invalid checksum.  I have very little experience with hex files so it will be helpful if you could provide more info.

**Comment by vivekannan** [comment]
My bad. Forgot to take the 2's complement of the checksum. Should work now. Thanks for reporting the bug. :)

**Comment by venkateshv6** [comment]
Thanks ,This bug is fixed
